# Generated by Django 5.0 on 2023-12-25 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='data',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='time',
        ),
        migrations.AddField(
            model_name='mail',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
