# Generated by Django 5.0 on 2023-12-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmail', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile-pics'),
        ),
    ]
