# Generated by Django 5.0 on 2023-12-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmail', '0006_profile_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='detail',
            field=models.TextField(default='Hello!'),
        ),
    ]
