# Generated by Django 5.0 on 2023-12-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmail', '0007_alter_profile_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='detail',
            field=models.CharField(max_length=100),
        ),
    ]
