# Generated by Django 5.0 on 2023-12-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmail', '0008_alter_profile_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='detail',
        ),
    ]
