# Generated by Django 5.0 on 2023-12-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmail', '0009_remove_profile_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
